name: audioenv
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - jupyterlab
  - librosa
  - lime
  - matplotlib
  - natsort
  - numpy
  - opendatasets
  - optuna
  - pandas
  - pip
  - pyts
  - pywavelets
  - requests
  - seaborn
  - shap
  - tqdm
  - widgetsnbextension
  - pathlib
  - pip:
    - pyroomacoustics
    - python-sofa
    - soundfile
    - torch
    - torchaudio
    - torchvision
