name: audioenv
channels:
  - conda-forge
  - defaults
dependencies:
  - librosa
  - pandas
  - jupyterlab
  - seaborn
  - matplotlib
  - opendatasets
  - pywavelets
  - pyts
  - optuna
  - interpret
  - widgetsnbextension
  - ipywidgets
  - pytorch
  - pytorch::torchaudio
  - shap
  - lime
  - pip
  - natsort
  - pathlib
  - pip:
    - pyroomacoustics